#!/bin/sh
# Xcode Cloud post-clone script: generate the gitignored Secrets.xcconfig from
# workflow environment variables, so cloud builds can resolve the base
# configuration reference ("Unable to open base configuration reference file"
# failure). Set these as custom environment variables on the Xcode Cloud workflow:
#   HF_TOKEN, PLACES_API_KEY, SUPABASE_REF, SUPABASE_ANON_KEY, APP_TOKEN
set -eu

WORKSPACE="${CI_WORKSPACE:-}"
if [ -z "$WORKSPACE" ]; then
  WORKSPACE="$(cd "$(dirname "$0")/.." && pwd)"
fi
OUT="$WORKSPACE/Secrets.xcconfig"

for v in HF_TOKEN PLACES_API_KEY SUPABASE_REF SUPABASE_ANON_KEY APP_TOKEN; do
  eval "val=\${$v:-}"
  if [ -z "$val" ]; then
    echo "warning: $v is not set in the Xcode Cloud environment; writing empty value" >&2
  fi
done

cat > "$OUT" <<EOF
// Generated by ci_scripts/ci_post_clone.sh from Xcode Cloud environment variables. Do not edit.
HF_TOKEN=${HF_TOKEN:-}
PLACES_API_KEY=${PLACES_API_KEY:-}
SUPABASE_REF=${SUPABASE_REF:-}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
APP_TOKEN=${APP_TOKEN:-}
EOF

echo "Wrote $OUT"
